### ISSUE TITLE
Another language

### ISSUE THREAD

**Issue by Mexikaner9** [rpsthecoder/js-speech-synthesis#7]
Thank you very much for your great example!
I would love to use the language German. Can you please tell me what I have to do. thank you in advance

**Comment by rpsthecoder** [comment]
Thanks @Mexikaner9. The [`getVoices()`](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices) method returns _all_ the available voices in a system (including German). You'll just need to choose the one you want for the speech.

In my code, if you want to use the first available German voice for speech, replace

`utterance.voice = getVoices()[0];`

with

`utterance.voice = getVoices().find(function(val){return val.lang === 'de-DE'});`

**Comment by Mexikaner9** [comment]
Hi rpsthecoder

many thanks for your quick reply and your help!
Now it also works with the language german.
I really like your example very much. Thanks for this.
Have a great day!

**Comment by Mexikaner9** [comment]
First I thought the example also works perfectly with the German language, but unfortunately this is not so.
Unfortunately not even three are read completely.
This is my example:
 http://nirvana.bplaced.net/1 
If I use your original example with a text in German language, the complete text will be read out (but of course the language is not correct).
 http://nirvana.bplaced.net/0 
Do you have an explanation, why my example with the German language does not work properly?

**Comment by rpsthecoder** [comment]
Hi @Mexikaner9, your example (http://nirvana.bplaced.net/1) is working for me: the text is fully read, and my original code (http://nirvana.bplaced.net/0) won't work for German because it uses an English voice.

What do you mean by "_Unfortunately not even three are read completely._"? Not even three paragraphs are fully read? 

When you use German voice, does the speech stops abruptly? Is that what you're saying? Which browser are you using?

**Comment by Mexikaner9** [comment]
Hi rpsthecoder!
Thank you very much for your answer.
	
When you use German voice, does the speech stops abruptly? Is that what you're saying?
yes, the speech stops after 31 words. 
	
Which browser are you using?
I use Google Chrome

**Comment by Mexikaner9** [comment]
Two of my friends told me the example works perfect.
Thank you for your help!
